title: Tanner Patrom Notes
description: A website dedicated to notes I take as a student and other studies
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
