title: Tanner Patrom Notes
description: A website dedicated to notes I take as a student and other studies
remote_theme: pmarsceill/just-the-docs

url: https://physicalbit7.github.io/notes

aux_links:
  Template Repository: https://physicalbit7.github.io/notes
