title: Tanner's Notes
description: A website dedicated to notes I take as a student and other studies
remote_theme: pmarsceill/just-the-docs

url: https://physicalbit7.github.io/notes

aux_links:
  see on Github: https://github.com/PhysicalBit7/notes



# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

color_scheme: light

# For copy button on code
enable_copy_code_button: true







